;;; android-keybar-test.el --- Android keybar regressions -*- lexical-binding: t; -*-
;; Run: emacs --batch -Q -l tests/android-keybar-test.el
(require 'ert)
(require 'cl-lib)

(defvar doom-user-dir nil)
(defvar modifier-bar-mode nil)
(defvar tool-bar-mode nil)
(defvar tool-bar-button-margin nil)
(defvar tool-bar-button-relief nil)
(defvar tool-bar-always-show-default nil)
(defvar android-intercept-control-space nil)
(defvar overriding-text-conversion-style nil)
(defvar text-conversion-style nil)
(defconst android-keybar-test-config
  (expand-file-name "../+android-keybar.el"
                    (file-name-directory (or load-file-name buffer-file-name))))

(defun android-keybar-test-load-definitions ()
  "Load guarded definitions without running Android initialization."
  (let ((doom-user-dir (file-name-directory android-keybar-test-config)))
    (with-temp-buffer
      (insert-file-contents android-keybar-test-config)
      (goto-char (point-min))
      (condition-case nil
          (while t
            (let ((form (read (current-buffer))))
              (when (and (eq (car-safe form) 'when)
                         (equal (cadr form) '(eq system-type 'android)))
                (dolist (definition (cddr form))
                  (when (memq (car-safe definition) '(defun defvar defconst))
                    (eval definition t))))))
        (end-of-file nil)))))
(android-keybar-test-load-definitions)

(defun android-keybar-test-png-size (file)
  "Read FILE's PNG dimensions without relying on native image support."
  (with-temp-buffer
    (set-buffer-multibyte nil)
    (insert-file-contents-literally file nil 0 24)
    (let ((bytes (buffer-string)))
      (should (equal (substring bytes 0 8) (unibyte-string 137 80 78 71 13 10 26 10)))
      (should (equal (substring bytes 12 16) "IHDR"))
      (cl-labels ((uint32 (offset)
                    (let ((value 0))
                      (dotimes (i 4 value)
                        (setq value (+ (ash value 8) (aref bytes (+ offset i))))))))
        (cons (uint32 16) (uint32 20))))))

(ert-deftest android-keybar-visible-assets-are-one-and-a-half-times-taller ()
  ;; Source-canvas height is part of the UI contract: touch padding cannot
  ;; substitute for visibly taller blocks. Keep widths unchanged for one row.
  (let ((expected-height (/ (* 68 3) 2))
        (checked 0))
    (dolist (theme '("light" "dark"))
      (dolist (state '("idle" "armed" "locked"))
        (dolist (button my/android-keybar-buttons)
          (let ((file (expand-file-name
                       (format "%s/%s/%s.png" theme state (nth 3 button))
                       my/android-keybar-image-root)))
            (should (equal (android-keybar-test-png-size file)
                           (cons 152 expected-height)))
            (cl-incf checked))))
      (should (equal (android-keybar-test-png-size
                      (expand-file-name (concat theme "/collapse.png")
                                        my/android-keybar-image-root))
                     (cons 92 expected-height)))
      (cl-incf checked))
    (should (equal (android-keybar-test-png-size
                    (expand-file-name "spacer.png" my/android-keybar-image-root))
                   (cons 18 expected-height)))
    (should (= (1+ checked) 51))))

(ert-deftest android-keybar-taller-assets-preserve-total-row-height ()
  ;; Galaxy's current width fit is ~0.7813: 102 source pixels become 80px.
  (let ((image-height (ceiling (* 102 0.7813))))
    (should (= (+ image-height (* 2 my/android-keybar-vertical-padding)) 190))))

(defmacro android-keybar-test-with-state (&rest body)
  "Run BODY with isolated modifier and visibility state, stubbing native UI."
  (declare (indent 0) (debug t))
  `(let ((my/android-keybar-hidden nil)
         (my/android-keybar-manually-hidden nil)
         (my/android-keybar-keyboard-visible nil)
         (my/android-keybar-visibility-timer nil)
         (my/android-keybar-armed-modifiers nil)
         (my/android-keybar-locked-modifiers nil)
         (my/android-keybar-movement-active nil)
         (my/android-keybar-saved-translation nil)
         (my/android-keybar-saved-conversion-override nil)
         (modifier-bar-mode t)
         (tool-bar-mode t)
         (input-decode-map (make-sparse-keymap))
         (key-translation-map (make-sparse-keymap)))
     (cl-letf (((symbol-function 'modifier-bar-mode)
                (lambda (arg) (setq modifier-bar-mode (> arg 0))))
               ((symbol-function 'tool-bar-mode)
                (lambda (arg) (setq tool-bar-mode (> arg 0))))
               ((symbol-function 'force-mode-line-update) #'ignore)
               ((symbol-function 'redisplay) #'ignore)
               ((symbol-function 'my/android-keybar-apply-theme) #'ignore)
               ((symbol-function 'my/android-keybar-refresh) #'ignore)
               ((symbol-function 'my/android-keybar-clear-main-toolbar) #'ignore)
               ((symbol-function 'customize-set-variable) #'ignore)
               ((symbol-function 'global-set-key) #'ignore))
       ,@body)))

(defmacro android-keybar-test-with-geometry (&rest body)
  "Provide mutable HEIGHT, WIDTH and GEOMETRY to BODY's frame observations."
  (declare (indent 0) (debug t))
  `(let ((height 2205) (width 1080) (geometry '(0 0 1080 2340))
         frame-parameters)
     (cl-letf (((symbol-function 'frame-pixel-height) (lambda (&optional _) height))
               ((symbol-function 'frame-pixel-width) (lambda (&optional _) width))
               ((symbol-function 'frame-visible-p) (lambda (&optional _) t))
               ((symbol-function 'frame-monitor-attributes)
                (lambda (&rest _) (list (cons 'geometry geometry))))
               ((symbol-function 'frame-parameter)
                (lambda (_frame name) (alist-get name frame-parameters)))
               ((symbol-function 'set-frame-parameter)
                (lambda (_frame name value)
                  (setf (alist-get name frame-parameters) value))))
       ,@body)))

(ert-deftest android-keybar-desktop-load-is-inert ()
  (let ((system-type 'darwin)
        (window-size-change-functions '(ignore))
        (doom-load-theme-hook '(ignore))
        (doom-after-reload-hook '(ignore))
        (after-focus-change-function #'ignore)
        (input-decode-map (make-sparse-keymap))
        (my/android-keybar-hidden 'unchanged))
    (cl-letf (((symbol-function 'my/android-keybar-install)
               (lambda () (ert-fail "Desktop load installed Android UI")))
              ((symbol-function 'advice-add)
               (lambda (&rest _) (ert-fail "Desktop load added advice")))
              ((symbol-function 'advice-remove)
               (lambda (&rest _) (ert-fail "Desktop load removed advice")))
              ((symbol-function 'run-at-time)
               (lambda (&rest _) (ert-fail "Desktop load started a timer"))))
      (load android-keybar-test-config nil t))
    (should (equal window-size-change-functions '(ignore)))
    (should (equal doom-load-theme-hook '(ignore)))
    (should (equal doom-after-reload-hook '(ignore)))
    (should (eq after-focus-change-function #'ignore))
    (should (eq my/android-keybar-hidden 'unchanged))
    (should (equal input-decode-map '(keymap)))))

(ert-deftest android-keybar-docked-geometry-has-hysteresis ()
  (should-not (my/android-keybar-keyboard-geometry 2205 2340 nil))
  (should-not (my/android-keybar-keyboard-geometry 2100 2205 nil))
  (should (my/android-keybar-keyboard-geometry 1253 2205 nil))
  (should (my/android-keybar-keyboard-geometry 2100 2205 t))
  (should-not (my/android-keybar-keyboard-geometry 2205 2205 t)))

(ert-deftest android-keybar-manual-hide-survives-until-closed-then-open ()
  (android-keybar-test-with-state
    (setq my/android-keybar-hidden t)
    (my/android-keybar-update-visibility t)
    (should-not my/android-keybar-hidden)
    (my/android-keybar-hide)
    (should my/android-keybar-manually-hidden)
    (dotimes (_ 3) (my/android-keybar-update-visibility t))
    (should my/android-keybar-hidden)
    (should-not modifier-bar-mode)
    (should-not tool-bar-mode)
    (my/android-keybar-update-visibility nil)
    (should my/android-keybar-manually-hidden)
    (my/android-keybar-update-visibility t)
    (should-not my/android-keybar-manually-hidden)
    (should-not my/android-keybar-hidden)
    (should modifier-bar-mode)
    (should tool-bar-mode)))

(ert-deftest android-keybar-hide-removes-both-native-rows ()
  (android-keybar-test-with-state
    (my/android-keybar-hide t)
    (should my/android-keybar-hidden)
    (should-not my/android-keybar-manually-hidden)
    (should-not modifier-bar-mode)
    (should-not tool-bar-mode)))

(ert-deftest android-keybar-repeat-requests-do-not-resurrect-manually-hidden-row ()
  (android-keybar-test-with-state
    (android-keybar-test-with-geometry
      (my/android-keybar-sync-visibility)
      (setq height 1253)
      (my/android-keybar-sync-visibility)
      (my/android-keybar-hide)
      (cl-letf (((symbol-function 'my/android-keybar-schedule-visibility)
                 #'my/android-keybar-sync-visibility))
        (my/android-keybar-keyboard-request nil nil)
        (my/android-keybar-keyboard-request nil nil)
        (my/android-keybar-keyboard-request nil t))
      (dotimes (_ 3) (my/android-keybar-sync-visibility))
      (should my/android-keybar-keyboard-visible)
      (should my/android-keybar-manually-hidden)
      (should my/android-keybar-hidden))))

(ert-deftest android-keybar-gradual-opening-does-not-drag-baseline-down ()
  (android-keybar-test-with-state
    (android-keybar-test-with-geometry
      (my/android-keybar-sync-visibility)
      (dolist (next-height '(2100 1950 1800 1650 1500 1253))
        (setq height next-height)
        (my/android-keybar-sync-visibility))
      (should my/android-keybar-keyboard-visible)
      (should-not my/android-keybar-hidden)
      (setq height 2205)
      (my/android-keybar-sync-visibility)
      (should-not my/android-keybar-keyboard-visible)
      (should my/android-keybar-hidden))))

(ert-deftest android-keybar-orientation-does-not-reuse-open-hysteresis ()
  (android-keybar-test-with-state
    (android-keybar-test-with-geometry
      (my/android-keybar-sync-visibility)
      (setq height 1253)
      (my/android-keybar-sync-visibility)
      (should my/android-keybar-keyboard-visible)
      (setq width 2340 height 945 geometry '(0 0 2340 1080))
      (my/android-keybar-sync-visibility)
      (should-not my/android-keybar-keyboard-visible)
      (should my/android-keybar-hidden))))

(ert-deftest android-keybar-starting-with-keyboard-open-can-detect-first-close ()
  (android-keybar-test-with-state
    (android-keybar-test-with-geometry
      ;; No closed-height sample exists yet; monitor height includes 135px
      ;; of system bars and cannot be used with the tighter closing threshold.
      (setq height 1253)
      (my/android-keybar-sync-visibility)
      (should my/android-keybar-keyboard-visible)
      (setq height 2205)
      (my/android-keybar-sync-visibility)
      (should-not my/android-keybar-keyboard-visible)
      (should my/android-keybar-hidden))))

(ert-deftest android-keybar-install-preserves-input-and-modifier-state ()
  (android-keybar-test-with-state
    (setq my/android-keybar-armed-modifiers '(shift)
          my/android-keybar-locked-modifiers '(control meta)
          my/android-keybar-movement-active t
          my/android-keybar-keyboard-visible t
          my/android-keybar-saved-translation '(t . preserved)
          my/android-keybar-saved-conversion-override '(t . preserved))
    (define-key key-translation-map [t] #'my/android-keybar-translate-locked)
    (my/android-keybar-install)
    (should (equal my/android-keybar-armed-modifiers '(shift)))
    (should (equal my/android-keybar-locked-modifiers '(control meta)))
    (should my/android-keybar-movement-active)
    (should (equal my/android-keybar-saved-translation '(t . preserved)))
    (should (equal my/android-keybar-saved-conversion-override '(t . preserved)))
    (should (eq (lookup-key key-translation-map [t])
                #'my/android-keybar-translate-locked))
    (cl-letf (((symbol-function 'my/android-keybar-flash-button) #'ignore))
      (should (equal (funcall (lookup-key input-decode-map [tool-bar escape]) nil)
                     [escape]))
      (should (equal (funcall (lookup-key input-decode-map [tool-bar tab]) nil)
                     [9])))
    (should (eq (my/android-keybar-apply-modifiers 9 '(shift)) 'backtab))
    (should (eq (lookup-key input-decode-map [tool-bar movement])
                #'my/android-keybar-movement-decoder))
    (should (eq (lookup-key input-decode-map [tool-bar collapse])
                #'my/android-keybar-hide-decoder))))

(ert-deftest android-keybar-hidden-install-does-not-reset-manual-latch ()
  (android-keybar-test-with-state
    (setq my/android-keybar-manually-hidden t
          my/android-keybar-keyboard-visible t)
    (my/android-keybar-install)
    (should my/android-keybar-manually-hidden)
    (should my/android-keybar-hidden)
    (should-not modifier-bar-mode)
    (should-not tool-bar-mode)))

(ert-deftest android-keybar-visibility-mutation-is-deferred-and-coalesced ()
  (android-keybar-test-with-state
    (let ((my/android-keybar-visibility-timer 'old-timer)
          canceled queued)
      (cl-letf (((symbol-function 'timerp)
                 (lambda (object) (memq object '(old-timer next-timer))))
                ((symbol-function 'cancel-timer)
                 (lambda (timer) (push timer canceled)))
                ((symbol-function 'run-at-time)
                 (lambda (delay repeat function &rest args)
                   (should (zerop delay))
                   (should-not repeat)
                   (push (cons function args) queued)
                   'next-timer))
                ((symbol-function 'my/android-keybar-sync-visibility)
                 (lambda (&rest _) (ert-fail "Visibility changed inside size hook"))))
        (my/android-keybar-schedule-visibility)
        (my/android-keybar-schedule-visibility)
        (should (equal (nreverse canceled) '(old-timer next-timer)))
        (should (= (length queued) 2))
        (should (eq my/android-keybar-visibility-timer 'next-timer))))))

(ert-deftest android-keybar-return-exits-movement-without-releasing-other-locks ()
  (android-keybar-test-with-state
    (cl-letf (((symbol-function 'my/android-keybar-sync-lock) #'ignore))
      (dolist (event '(return linefeed newline 10 13))
        (setq my/android-keybar-locked-modifiers '(control meta)
              my/android-keybar-movement-active t)
        (should (= 13 (my/android-keybar-apply-modifiers event '(control meta))))
        (should-not my/android-keybar-movement-active)
        (should (equal my/android-keybar-locked-modifiers '(meta)))))))

(ert-run-tests-batch-and-exit "^android-keybar-")
