;;; android-dashboard-test.el --- Android landing-screen regressions -*- lexical-binding: t; -*-
;; Run: emacs --batch -Q -l tests/android-dashboard-test.el
(require 'ert)
(require 'cl-lib)
(require 'bookmark)
(require 'hl-line)
(defvar +dashboard-functions nil)
(defvar +dashboard-name "*doom*")
(defvar +dashboard-anchor nil)
(defvar +dashboard-mode-hook nil)
(defvar +doom-dashboard-mode-hook nil)
(defvar hide-mode-line-mode nil)
(defvar touch-screen-display-keyboard)
(defconst android-dashboard-test-config
  (expand-file-name "../+android-dashboard.el"
                    (file-name-directory (or load-file-name buffer-file-name))))

(let ((system-type 'android)
      (+dashboard-functions nil)
      (+dashboard-mode-hook nil)
      (+doom-dashboard-mode-hook nil))
  (load android-dashboard-test-config nil t))

(ert-deftest android-dashboard-desktop-settings-untouched ()
  (let ((system-type 'darwin)
        (+dashboard-functions '(desktop-widget))
        (+dashboard-anchor '(center . left))
        (+dashboard-mode-hook nil)
        (+doom-dashboard-mode-hook nil))
    (load android-dashboard-test-config nil t)
    (should (equal +dashboard-functions '(desktop-widget)))
    (should (equal +dashboard-anchor '(center . left)))
    (should-not +dashboard-mode-hook)
    (should-not +doom-dashboard-mode-hook)))

(ert-deftest android-dashboard-bookmark-recency-does-not-mutate-records ()
  (let* ((bookmark-alist '(("old" (last-modified . (0 1)))
                           ("new" (last-modified . (0 30)))
                           ("legacy one" (filename . "one"))
                           ("middle" (last-modified . (0 20)))
                           ("legacy two" (filename . "two"))
                           ("last" (filename . "last"))))
         (before (copy-tree bookmark-alist))
         (bookmark-sort-flag t))
    (cl-letf (((symbol-function 'bookmark-maybe-load-default-file) #'ignore))
      (should (equal (my/android-dashboard-recent-bookmarks)
                     '("new" "middle" "old" "legacy one" "legacy two")))
      (should (equal bookmark-alist before))
      (should (eq bookmark-sort-flag t)))))

(ert-deftest android-dashboard-bookmarks-deduplicate-stacked-names ()
  (let ((bookmark-alist '(("same" (last-modified . (0 3)))
                          ("same" (last-modified . (0 2)))
                          ("other" (last-modified . (0 1))))))
    (cl-letf (((symbol-function 'bookmark-maybe-load-default-file) #'ignore))
      (should (equal (my/android-dashboard-recent-bookmarks) '("same" "other"))))))

(ert-deftest android-dashboard-empty-bookmarks-preserve-quiet-wordmark ()
  (let ((bookmark-alist nil)
        (text-scale-mode-amount -1))
    (cl-letf (((symbol-function 'bookmark-maybe-load-default-file) #'ignore))
      (with-temp-buffer
        (my/android-dashboard-wordmark)
        (should (equal (buffer-substring-no-properties (point-min) (point-max))
                       " \nD O O M\nE M A C S\n"))
        (should-not (next-button (point-min)))
        (should (= text-scale-mode-amount -1))))))

(ert-deftest android-dashboard-render-rehides-modeline-after-doom-overrides-it ()
  (let ((bookmark-alist nil)
        (global-format (default-value 'mode-line-format))
        (calls 0)
        (original-require (symbol-function 'require)))
    (cl-letf (((symbol-function 'bookmark-maybe-load-default-file) #'ignore)
              ((symbol-function 'require)
               (lambda (feature &rest args)
                 (if (eq feature 'hide-mode-line) t
                   (apply original-require feature args))))
              ((symbol-function 'hide-mode-line-mode)
               (lambda (arg)
                 (should (= arg 1))
                 (cl-incf calls)
                 (setq-local hide-mode-line-mode t mode-line-format nil))))
      (with-temp-buffer
        ;; Existing dashboards need this even when their minor-mode flag is t.
        (setq-local hide-mode-line-mode t mode-line-format '(dashboard-format))
        (my/android-dashboard-wordmark)
        (should-not mode-line-format)
        (setq-local mode-line-format '(dashboard-format))
        (erase-buffer)
        (my/android-dashboard-wordmark)
        (should-not mode-line-format)
        (should (= calls 2)))
      (should (equal (default-value 'mode-line-format) global-format)))))

(ert-deftest android-dashboard-buttons-retain-full-name-and-action ()
  (let ((name "a long bookmark name containing 日本語\nand a newline")
        activated)
    (with-temp-buffer
      (insert (my/android-dashboard-bookmark-button name 20))
      (should (= (string-width (buffer-string)) 20))
      (should-not (string-match-p "[\n\r\t]" (buffer-string)))
      (let ((button (button-at (point-min))))
        (should (button-get button 'follow-link))
        (should (eq (button-get button 'mouse-face) 'highlight))
        (should (eq (plist-get (button-get button 'face) :inherit) 'default))
        (cl-letf (((symbol-function 'bookmark-jump)
                   (lambda (target) (setq activated target))))
          (button-activate button)
          (should (equal activated name)))))))

(ert-deftest android-dashboard-buttons-use-current-theme-background ()
  (cl-letf (((symbol-function 'my/android-dashboard-block-background)
             (lambda () "#eeeeee"))
            ((symbol-function 'face-foreground) (lambda (&rest _) "#222222")))
    (with-temp-buffer
      (insert (my/android-dashboard-bookmark-button "life" 20))
      (let ((face (button-get (button-at (point-min)) 'face)))
        (should (equal (plist-get face :background) "#eeeeee"))
        (should (equal (plist-get face :foreground) "#222222"))
        (should-not (plist-member face :family))
        (should-not (plist-member face :height))))))

(ert-deftest android-dashboard-button-map-isolated-and-explicit ()
  (should-not (eq my/android-dashboard-button-map button-map))
  (should (eq (lookup-key my/android-dashboard-button-map [down-mouse-1]) #'ignore))
  (dolist (event '([mouse-1] [mouse-2] [touchscreen-down]))
    (should (eq (lookup-key my/android-dashboard-button-map event)
                #'my/android-dashboard-push-button)))
  ;; Do not replace the standard button bindings in other buffers.
  (should-not (eq (lookup-key button-map [mouse-1]) #'my/android-dashboard-push-button))
  (should-not (eq (lookup-key button-map [touchscreen-down])
                  #'my/android-dashboard-push-button))
  (should (equal (lookup-key my/android-dashboard-button-map (kbd "RET"))
                 (lookup-key button-map (kbd "RET"))))
  (with-temp-buffer
    (insert (my/android-dashboard-bookmark-button "test bookmark" 20))
    (should (eq (button-get (button-at (point-min)) 'keymap)
                my/android-dashboard-button-map))))

(ert-deftest android-dashboard-button-command-forwards-translated-event ()
  (let* ((event '(mouse-1 (test-window 42 (10 . 20) 0)))
         (last-command-event event)
         (last-input-event '(touchscreen-end (test-window 1 (10 . 20) 0)))
         received)
    (cl-letf (((symbol-function 'push-button)
               (lambda (position &rest _)
                 (setq received position)
                 'activated)))
      (should (eq (call-interactively #'my/android-dashboard-push-button) 'activated))
      (should (eq received event)))))

(ert-deftest android-dashboard-button-command-preserves-keyboard-activation ()
  (with-temp-buffer
    (insert "button")
    (goto-char 3)
    (let ((last-command-event 13)
          (last-input-event '(touchscreen-end stale-position))
          received)
      (cl-letf (((symbol-function 'push-button)
                 (lambda (position &rest _)
                   (setq received position)
                   t)))
        (should (call-interactively #'my/android-dashboard-push-button))
        (should (= received 3))))))

(ert-deftest android-dashboard-raw-touch-down-delegates-tap-tracking ()
  ;; push-button owns waiting for the matching release; forwarding the raw
  ;; event intact retains its drag/cancellation handling instead of activating
  ;; the stale dashboard point immediately.
  (let* ((event '(touchscreen-down (test-window 42 (10 . 20) 0)))
         (last-command-event event)
         received)
    (cl-letf (((symbol-function 'push-button)
               (lambda (position &rest _) (setq received position) t)))
      (should (call-interactively #'my/android-dashboard-push-button))
      (should (eq received event)))))

(ert-deftest android-dashboard-click-activates-event-button-not-old-point ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (insert (my/android-dashboard-bookmark-button "first" 20) "\n")
      (let ((second (point))
            activated)
        (insert (my/android-dashboard-bookmark-button "second" 20) "\n")
        (goto-char (point-min))
        (let ((last-command-event
               (list 'mouse-1 (list (selected-window) second '(0 . 0) 0)))
              (last-input-event '(touchscreen-end stale-position)))
          (cl-letf (((symbol-function 'bookmark-jump)
                     (lambda (name) (push name activated))))
            (should (call-interactively #'my/android-dashboard-push-button))
            (should (equal activated '("second")))))))))

(ert-deftest android-dashboard-background-release-opens-keyboard-only-off-buttons ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (insert (my/android-dashboard-bookmark-button "bookmark" 20) "\n\n")
      (let ((button-event (list 'mouse-1 (list (selected-window) 1 '(0 . 0) 0)))
            (background-event
             (list 'mouse-1 (list (selected-window) (1- (point-max)) '(0 . 0) 0)))
            (keyboard-count 0)
            activated)
        (cl-letf (((symbol-function 'bookmark-jump)
                   (lambda (name) (push name activated)))
                  ((symbol-function 'frame-toggle-on-screen-keyboard)
                   (lambda (frame hide)
                     (should-not frame)
                     (should-not hide)
                     (cl-incf keyboard-count))))
          (my/android-dashboard-background-tap button-event)
          (should (equal activated '("bookmark")))
          (should (= keyboard-count 0))
          (my/android-dashboard-background-tap background-event)
          (should (= keyboard-count 1))
          (should (equal activated '("bookmark"))))))))

(ert-deftest android-dashboard-keyboard-on-release-is-buffer-local ()
  (let ((touch-screen-display-keyboard t)
        (original-require (symbol-function 'require))
        (keyboard-count 0))
    (cl-letf (((symbol-function 'require)
               (lambda (feature &rest args)
                 (unless (eq feature 'hide-mode-line)
                   (apply original-require feature args))))
              ((symbol-function 'frame-toggle-on-screen-keyboard)
               (lambda (&rest _) (cl-incf keyboard-count))))
      (with-temp-buffer
        (use-local-map (make-sparse-keymap))
        (my/android-dashboard-quiet-mode)
        (should (local-variable-p 'touch-screen-display-keyboard))
        (should-not touch-screen-display-keyboard)
        (should (eq (lookup-key (current-local-map) [mouse-1])
                    #'my/android-dashboard-background-tap))
        ;; Neither the setup hook nor touch-down requests a keyboard resize.
        (should-not (lookup-key (current-local-map) [down-mouse-1]))
        (should-not (lookup-key (current-local-map) [touchscreen-down]))
        (should (= keyboard-count 0)))
      (with-temp-buffer
        (should touch-screen-display-keyboard)
        (should-not (local-variable-p 'touch-screen-display-keyboard)))
      (should (default-value 'touch-screen-display-keyboard)))))

(ert-deftest android-dashboard-block-prefers-a-distinct-theme-background ()
  (cl-letf (((symbol-function 'face-background)
             (lambda (face &rest _)
               (if (eq face 'mode-line-inactive) "#222222" "#000000")))
            ((symbol-function 'color-name-to-rgb)
             (lambda (color) (if (equal color "#222222") '(0.13 0.13 0.13) '(0 0 0)))))
    (should (equal (my/android-dashboard-block-background) "#222222"))))

(ert-deftest android-dashboard-block-blends-flat-themes-in-light-and-dark ()
  (dolist (dark '(nil t))
    (cl-letf (((symbol-function 'face-background)
               (lambda (&rest _) (if dark "black" "white")))
              ((symbol-function 'face-foreground)
               (lambda (&rest _) (if dark "white" "black")))
              ((symbol-function 'color-name-to-rgb)
               (lambda (color) (if (equal color "black") '(0 0 0) '(1 1 1)))))
      (should (equal (my/android-dashboard-block-background)
                     (if dark "#191919" "#e5e5e5"))))))

(ert-deftest android-dashboard-renders-five-buttons-with-narrow-width ()
  (let ((bookmark-alist '(("one very long bookmark name") ("two") ("three")
                          ("four") ("five") ("six"))))
    (cl-letf (((symbol-function 'bookmark-maybe-load-default-file) #'ignore)
              ((symbol-function 'window-body-width) (lambda (&rest _) 180))
              ((symbol-function 'window-font-width) (lambda (&rest _) 10)))
      (with-temp-buffer
        (my/android-dashboard-bookmarks)
        (let ((position (point-min)) names)
          (while-let ((button (next-button position)))
            (push (button-get button 'my/android-dashboard-bookmark) names)
            ;; Eighteen visible cells, minus the four-cell outer safety margin.
            (should (= (string-width (buffer-substring-no-properties
                                      (button-start button) (button-end button)))
                       14))
            (setq position (button-end button)))
          (should (equal (nreverse names)
                         '("one very long bookmark name" "two" "three" "four" "five"))))))))

(ert-deftest android-dashboard-bookmarks-have-configurable-wordmark-gap ()
  (let ((my/android-dashboard-bookmark-gap 3.0))
    (cl-letf (((symbol-function 'my/android-dashboard-recent-bookmarks)
               (lambda () '("test bookmark"))))
      (with-temp-buffer
        (my/android-dashboard-bookmarks)
        (should (equal (buffer-substring-no-properties (point-min) (+ (point-min) 3))
                       "\n\n\n"))
        (should-not (get-text-property (point-min) 'line-height))
        (should (button-at (+ (point-min) 3)))))))

(defun android-dashboard-test-upstream-resize (&rest _)
  "Reproduce Doom's affected point-restoration branch without loading Doom.
These are the relevant forms of `+dashboard-resize-h': the window loop is
outside its later `with-current-buffer' body.  Keep this fixture unguarded
so the regression demonstrates the failure before applying our advice."
  (when-let* ((windows (get-buffer-window-list (get-buffer +dashboard-name) nil t)))
    (dolist (w windows)
      (when-let* ((pos (window-parameter w '+dashboard-last-position)))
        (goto-char pos)
        ;; The relevant non-region branch of +dashboard-reposition-point-h.
        (when (eq (current-buffer) (get-buffer +dashboard-name))
          (unless (button-at (point))
            (forward-button 1 nil nil t)))))))

(ert-deftest android-dashboard-resize-restores-only-dashboard-point ()
  (let ((dashboard (generate-new-buffer " *dashboard-resize-test*"))
        (editing (generate-new-buffer " *dashboard-edit-test*")))
    (unwind-protect
        (save-window-excursion
          (delete-other-windows)
          (switch-to-buffer editing)
          (insert (make-string 1000 ?x))
          (with-current-buffer dashboard
            (insert "\n\n\n")
            (insert-text-button "bookmark")
            (insert "\n"))
          (let* ((+dashboard-name (buffer-name dashboard))
                 (editing-window (selected-window))
                 (dashboard-window (split-window-below)))
            (set-window-buffer dashboard-window dashboard)
            (set-window-parameter dashboard-window '+dashboard-last-position 1)
            ;; Prove the exact upstream ordering clobbers the unrelated point.
            (goto-char 900)
            (android-dashboard-test-upstream-resize)
            (should (= (point) 1))
            ;; The fixed call retains editing point, window and current buffer,
            ;; while the dashboard's normal button-restoration logic still runs.
            (goto-char 900)
            (my/android-dashboard-resize-in-buffer
             #'android-dashboard-test-upstream-resize)
            (should (= (point) 900))
            (should (eq (current-buffer) editing))
            (should (eq (selected-window) editing-window))
            (with-current-buffer dashboard
              (should (= (point) 4))
              (should (button-at (point))))))
      (kill-buffer dashboard)
      (kill-buffer editing))))

(ert-deftest android-dashboard-resize-without-dashboard-passes-through ()
  (let ((+dashboard-name " *absent-dashboard-for-resize-test*"))
    (with-temp-buffer
      (insert "editing")
      (goto-char 4)
      (let ((original-buffer (current-buffer)))
        (should
         (eq (my/android-dashboard-resize-in-buffer
              (lambda (arg)
                (should (eq (current-buffer) original-buffer))
                (should (= (point) 4))
                arg)
              'unchanged)
             'unchanged))
        (should (= (point) 4))))))

(ert-deftest android-dashboard-resize-error-restores-calling-buffer ()
  (let ((dashboard (generate-new-buffer " *dashboard-resize-error-test*")))
    (unwind-protect
        (let ((+dashboard-name (buffer-name dashboard)))
          (with-temp-buffer
            (insert "editing")
            (goto-char 4)
            (let ((original-buffer (current-buffer)))
              (should-error
               (my/android-dashboard-resize-in-buffer
                (lambda ()
                  (should (eq (current-buffer) dashboard))
                  (error "Test resize error"))))
              (should (eq (current-buffer) original-buffer))
              (should (= (point) 4)))))
      (kill-buffer dashboard))))

(ert-deftest android-dashboard-centers-measured-content-not-fixed-line-count ()
  (let ((buffer (get-buffer-create "*doom*")))
    (unwind-protect
        (with-current-buffer buffer
          (erase-buffer)
          (insert (propertize " " 'my/android-dashboard-spacer t)
                  "\nD O O M\nE M A C S\nbookmark\n")
          (cl-letf (((symbol-function 'get-buffer-window) (lambda (&rest _) 'test-window))
                    ((symbol-function 'window-text-pixel-size)
                     (lambda (_window from to &rest _)
                       (if (= from 1)
                           (progn (should (= to 3)) '(1 . 20))
                         (progn (should (= from 3)) '(200 . 400)))))
                    ((symbol-function 'window-body-height) (lambda (&rest _) 1000)))
            (my/android-dashboard-center-wordmark)
            ;; 300px = 15 plain lines: one permanent anchor plus 14 newlines.
            (should (= (next-single-property-change
                        3 'my/android-dashboard-padding nil (point-max)) 17))
            (should (= (line-number-at-pos 17) 16))
            (should-not (text-property-not-all (point-min) (point-max) 'display nil))
            (should-not (text-property-not-all (point-min) 17 'line-height nil))))
      (kill-buffer buffer))))

(ert-deftest android-dashboard-short-window-clamps-padding ()
  (let ((buffer (get-buffer-create "*doom*")))
    (unwind-protect
        (with-current-buffer buffer
          (erase-buffer)
          (insert (propertize " " 'my/android-dashboard-spacer t) "\nbody\n")
          (cl-letf (((symbol-function 'get-buffer-window) (lambda (&rest _) 'test-window))
                    ((symbol-function 'window-text-pixel-size)
                     (lambda (_window from &rest _)
                       (if (= from 1) '(1 . 20) '(200 . 400))))
                    ((symbol-function 'window-body-height) (lambda (&rest _) 200)))
            (my/android-dashboard-center-wordmark)
            (should (equal (buffer-substring-no-properties (point-min) (point-max))
                           " \nbody\n"))
            (should-not (get-text-property (point-min) 'display))))
      (kill-buffer buffer))))

(ert-deftest android-dashboard-padding-recalculates-without-moving-content-point ()
  (let ((buffer (get-buffer-create "*doom*"))
        (height 1000)
        (line-height 20))
    (unwind-protect
        (with-current-buffer buffer
          (erase-buffer)
          ;; Include the obsolete stretched glyph to exercise hot migration.
          (insert (propertize " " 'my/android-dashboard-spacer t
                              'display '(space :width (0) :height (758)))
                  "\nbody\n")
          (goto-char 3)
          (cl-letf (((symbol-function 'get-buffer-window) (lambda (&rest _) 'test-window))
                    ((symbol-function 'window-text-pixel-size)
                     (lambda (_window from &rest _)
                       (if (= from 1) (cons 1 line-height) '(200 . 400))))
                    ((symbol-function 'window-body-height) (lambda (&rest _) height)))
            (my/android-dashboard-center-wordmark)
            (should (= (point) 17))
            (should (eq (char-after) ?b))
            (let ((text (buffer-string)))
              (my/android-dashboard-center-wordmark)
              (should (equal (buffer-string) text)))
            ;; A taller remapped font needs fewer plain lines for the same gap.
            (setq line-height 30)
            (my/android-dashboard-center-wordmark)
            (should (= (point) 12))
            (should (eq (char-after) ?b))
            ;; Closing the available height removes only our padding.
            (setq height 400)
            (my/android-dashboard-center-wordmark)
            (should (= (point) 3))
            (should (eq (char-after) ?b))
            (should (equal (buffer-substring-no-properties (point-min) (point-max))
                           " \nbody\n"))
            (should-not (get-text-property (point-min) 'display))))
      (kill-buffer buffer))))

(ert-run-tests-batch-and-exit)
